//
// Generated file, do not edit! Created by nedtool 5.0 from ack_join.msg.
//

#ifndef __ACK_JOIN_M_H
#define __ACK_JOIN_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ack_join.msg:2</tt> by nedtool.
 * <pre>
 * message Ack_join_msg
 * {
 * }
 * </pre>
 */
class Ack_join_msg : public ::omnetpp::cMessage
{
  protected:

  private:
    void copy(const Ack_join_msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Ack_join_msg&);

  public:
    Ack_join_msg(const char *name=nullptr, int kind=0);
    Ack_join_msg(const Ack_join_msg& other);
    virtual ~Ack_join_msg();
    Ack_join_msg& operator=(const Ack_join_msg& other);
    virtual Ack_join_msg *dup() const {return new Ack_join_msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Ack_join_msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Ack_join_msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ACK_JOIN_M_H

