//
// Generated file, do not edit! Created by nedtool 5.0 from ack_leave.msg.
//

#ifndef __ACK_LEAVE_M_H
#define __ACK_LEAVE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ack_leave.msg:4</tt> by nedtool.
 * <pre>
 * message Ack_leave_msg
 * {
 *     int destId;
 * }
 * </pre>
 */
class Ack_leave_msg : public ::omnetpp::cMessage
{
  protected:
    int destId;

  private:
    void copy(const Ack_leave_msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Ack_leave_msg&);

  public:
    Ack_leave_msg(const char *name=nullptr, int kind=0);
    Ack_leave_msg(const Ack_leave_msg& other);
    virtual ~Ack_leave_msg();
    Ack_leave_msg& operator=(const Ack_leave_msg& other);
    virtual Ack_leave_msg *dup() const {return new Ack_leave_msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getDestId() const;
    virtual void setDestId(int destId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Ack_leave_msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Ack_leave_msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ACK_LEAVE_M_H

