//
// Generated file, do not edit! Created by nedtool 4.6 from broker_init.msg.
//

#ifndef _BROKER_INIT_M_H_
#define _BROKER_INIT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>broker_init.msg:2</tt> by nedtool.
 * <pre>
 * message Broker_init_msg
 * {
 *     int srcId;
 * }
 * </pre>
 */
class Broker_init_msg : public ::cMessage
{
  protected:
    int srcId_var;

  private:
    void copy(const Broker_init_msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Broker_init_msg&);

  public:
    Broker_init_msg(const char *name=NULL, int kind=0);
    Broker_init_msg(const Broker_init_msg& other);
    virtual ~Broker_init_msg();
    Broker_init_msg& operator=(const Broker_init_msg& other);
    virtual Broker_init_msg *dup() const {return new Broker_init_msg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);
};

inline void doPacking(cCommBuffer *b, Broker_init_msg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Broker_init_msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _BROKER_INIT_M_H_

