//
// Generated file, do not edit! Created by nedtool 5.0 from broker_init.msg.
//

#ifndef __BROKER_INIT_M_H
#define __BROKER_INIT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>broker_init.msg:2</tt> by nedtool.
 * <pre>
 * message Broker_init_msg
 * {
 *     int srcId; //TODO: really needed?
 * }
 * </pre>
 */
class Broker_init_msg : public ::omnetpp::cMessage
{
  protected:
    int srcId;

  private:
    void copy(const Broker_init_msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Broker_init_msg&);

  public:
    Broker_init_msg(const char *name=nullptr, int kind=0);
    Broker_init_msg(const Broker_init_msg& other);
    virtual ~Broker_init_msg();
    Broker_init_msg& operator=(const Broker_init_msg& other);
    virtual Broker_init_msg *dup() const {return new Broker_init_msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Broker_init_msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Broker_init_msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __BROKER_INIT_M_H

