//
// Generated file, do not edit! Created by nedtool 5.0 from join.msg.
//

#ifndef __JOIN_M_H
#define __JOIN_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>join.msg:4</tt> by nedtool.
 * <pre>
 * message Join_msg
 * {
 *     int srcId;
 * }
 * </pre>
 */
class Join_msg : public ::omnetpp::cMessage
{
  protected:
    int srcId;

  private:
    void copy(const Join_msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Join_msg&);

  public:
    Join_msg(const char *name=nullptr, int kind=0);
    Join_msg(const Join_msg& other);
    virtual ~Join_msg();
    Join_msg& operator=(const Join_msg& other);
    virtual Join_msg *dup() const {return new Join_msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Join_msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Join_msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __JOIN_M_H

