//
// Generated file, do not edit! Created by nedtool 5.0 from leave.msg.
//

#ifndef __LEAVE_M_H
#define __LEAVE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>leave.msg:4</tt> by nedtool.
 * <pre>
 * message Leave_msg
 * {
 *     int srcId;
 * }
 * </pre>
 */
class Leave_msg : public ::omnetpp::cMessage
{
  protected:
    int srcId;

  private:
    void copy(const Leave_msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Leave_msg&);

  public:
    Leave_msg(const char *name=nullptr, int kind=0);
    Leave_msg(const Leave_msg& other);
    virtual ~Leave_msg();
    Leave_msg& operator=(const Leave_msg& other);
    virtual Leave_msg *dup() const {return new Leave_msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Leave_msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Leave_msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __LEAVE_M_H

