//
// Generated file, do not edit! Created by nedtool 5.0 from subscribe.msg.
//

#ifndef __SUBSCRIBE_M_H
#define __SUBSCRIBE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>subscribe.msg:4</tt> by nedtool.
 * <pre>
 * message Subscribe_msg
 * {
 *     int srcId = -1;//TODO, REALLY NEEDED? the server has the gate, is it sufficient?
 *     int topic = -1;
 * }
 * </pre>
 */
class Subscribe_msg : public ::omnetpp::cMessage
{
  protected:
    int srcId;
    int topic;

  private:
    void copy(const Subscribe_msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Subscribe_msg&);

  public:
    Subscribe_msg(const char *name=nullptr, int kind=0);
    Subscribe_msg(const Subscribe_msg& other);
    virtual ~Subscribe_msg();
    Subscribe_msg& operator=(const Subscribe_msg& other);
    virtual Subscribe_msg *dup() const {return new Subscribe_msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);
    virtual int getTopic() const;
    virtual void setTopic(int topic);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Subscribe_msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Subscribe_msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SUBSCRIBE_M_H

