//
// Generated file, do not edit! Created by nedtool 4.6 from subscribe.msg.
//

#ifndef _SUBSCRIBE_M_H_
#define _SUBSCRIBE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>subscribe.msg:4</tt> by nedtool.
 * <pre>
 * message Subscribe_msg
 * {
 *     int srcId;//TODO, REALLY NEEDED?
 *     int topic;
 * }
 * </pre>
 */
class Subscribe_msg : public ::cMessage
{
  protected:
    int srcId_var;
    int topic_var;

  private:
    void copy(const Subscribe_msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Subscribe_msg&);

  public:
    Subscribe_msg(const char *name=NULL, int kind=0);
    Subscribe_msg(const Subscribe_msg& other);
    virtual ~Subscribe_msg();
    Subscribe_msg& operator=(const Subscribe_msg& other);
    virtual Subscribe_msg *dup() const {return new Subscribe_msg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);
    virtual int getTopic() const;
    virtual void setTopic(int topic);
};

inline void doPacking(cCommBuffer *b, Subscribe_msg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Subscribe_msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _SUBSCRIBE_M_H_

