//
// Generated file, do not edit! Created by nedtool 5.0 from unsubscribe.msg.
//

#ifndef __UNSUBSCRIBE_M_H
#define __UNSUBSCRIBE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>unsubscribe.msg:1</tt> by nedtool.
 * <pre>
 * message Unsubscribe_msg
 * {
 *     int topic;
 * }
 * </pre>
 */
class Unsubscribe_msg : public ::omnetpp::cMessage
{
  protected:
    int topic;

  private:
    void copy(const Unsubscribe_msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Unsubscribe_msg&);

  public:
    Unsubscribe_msg(const char *name=nullptr, int kind=0);
    Unsubscribe_msg(const Unsubscribe_msg& other);
    virtual ~Unsubscribe_msg();
    Unsubscribe_msg& operator=(const Unsubscribe_msg& other);
    virtual Unsubscribe_msg *dup() const {return new Unsubscribe_msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getTopic() const;
    virtual void setTopic(int topic);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Unsubscribe_msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Unsubscribe_msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __UNSUBSCRIBE_M_H

